config/routes.rb
Rails.application.routes.draw do
  get 'bids/new'

  get 'bids/create'

  root 'static_pages#home'

  
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}, skip: :registrations
  devise_scope :user do 
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'user',
      path_names: { new: 'sign_up'},
      controller: 'registrations',
      as: :user_registration do 
        get :cancel
      end
  end

  resources :users, only: [:show] do
		member do
			get :history
    end
    resources :reviews, only: [:create, :destroy, :index]
    resources :notifications, only: [:index]
  end

  resources :conversations, only: [:index, :show]
  resources :messages, only: [:create]

  resources :auctions do
    member do
      get :history, :comments
    end
    resources :bids, only: [:new, :create]
    resources :comments, only: [:create, :destroy]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :auction
  validates_presence_of :content, :auction, :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def create
    @auction = Auction.find(params[:auction_id])
    @auction.comments.build(
      content: comment_params[:content], user: current_user, auction: @auction
    )
    if @auction.save
      create_notification @auction 
      respond_to do |format|
        format.html {redirect_to comments_auction_path @auction}
        format.js
      end
    else
      flash[:failure] = "an error has occured while saving the comment"
      redirect_to comments_auction_path(@auction)
    end
  end

  def destroy
    @comment.destroy
    render json: {id: params[:id]}
  end
  
  private
    def comment_params
      params.require(:comment).permit(:content)
    end

    def create_notification(auction)
      return if auction.owner == current_user
      Notification.notify_new_comment(auction, current_user)
    end

    def correct_user
      @comment = current_user.comments.find(params[:id])
      redirect_to root_path if @comment.nil?
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def is_owner(comment)
    current_user == comment.user
  end
end

app/views/comments/_comment.html.erb
<div class="row comment" id="<%= 'comment-'+comment.id.to_s %>"> 
  <% if is_owner(comment) %>
    <%=link_to auction_comment_path(@auction,comment), 
      remote:true, method: :delete, class: "close comment-close" do%>
      <span>&times;</span>
    <% end %>
  <% end %>

  <div class="col-md-3 text-center">
    <%= link_to user_path(comment.user), class: "thumb thumb-round" do %>
      <%= image_tag profile_thumb_url(comment.user) %>
    <% end %>
    <div><%=comment.user.display_name.capitalize%></div>
  </div>

  <div class="col-md-9 comment-content light-text" >
    <div><%= time_ago_in_words(comment.created_at)%> ago </div>
    <%= comment.content %>
  </div>
</div>

app/views/comments/create.js.erb
$("#comments").append("<%=j render @auction.comments.last %>").children(":last").hide().slideDown(500);
$("#comment_body").val("")