config/routes.rb
Rails.application.routes.draw do
  get 'bids/new'

  get 'bids/create'

  root 'static_pages#home'

  
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}, skip: :registrations
  devise_scope :user do 
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'user',
      path_names: { new: 'sign_up'},
      controller: 'registrations',
      as: :user_registration do 
        get :cancel
      end
  end

  resources :users, only: [:show] do
		member do
			get :history
    end
    resources :reviews, only: [:create, :destroy, :index]
    resources :notifications, only: [:index]
  end

  resources :conversations, only: [:index, :show]
  resources :messages, only: [:create]

  resources :auctions do
    member do
      get :history, :comments
    end
    resources :bids, only: [:new, :create]
    resources :comments, only: [:create, :destroy]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable, :omniauth_providers => [:facebook]
  validates_presence_of :display_name
  validate :picture_size
  mount_uploader :picture, AvatarUploader 

  has_many :auctions, dependent: :destroy, foreign_key: 'owner_id' 
  has_many :bids, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reviews_written, class_name:'Review', dependent: :destroy, foreign_key: 'giver_id'
  has_many :reviews_received, class_name:'Review', dependent: :destroy, foreign_key: 'receiver_id'
  has_many :notifications, dependent: :destroy

  def conversations
    Conversation.where("sender_id = ? OR recipient_id = ?", self.id, self.id)
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.display_name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.confirmed_at = Time.now.getutc
    end
  end
	
	def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  #is there a more rails way??
  def auctions_won
    Auction
    .expired
    .joins(:bids)
    .where("bids.user_id = ?", id)
    .where('(bids.auction_id, bids.bid_amount) in (select auctions.id, max(bids.bid_amount) from auctions, bids where bids.auction_id = auctions.id group by auctions.id )')
  end

  def active_auctions
    auctions.active
  end

  #is there a more rails way??
  def active_bids
    bids.where("(bids.auction_id, bids.bid_amount) in (select auctions.id, max(bids.bid_amount) from bids, auctions where bids.auction_id = auctions.id AND auctions.brought_out = 'f' group by auctions.id)")
    .order(created_at: :desc)
  end  

  def unread_notification_count
    notifications.where(read: false).count
  end

  def unread_message_count
    conversations.joins(:messages)
      .where('messages.read = ? And messages.user_id != ?', false, self.id).count
  end

  def read_all_messages
    Message.joins(:conversation)
      .where("sender_id = ? OR recipient_id = ?", self.id, self.id)
      .where('messages.read = ? And messages.user_id != ?', false, self.id).update_all(read: true)
  end

  def is_part_of_convo(conversation_id)
    conversation_id && conversations.exists?(conversation_id)
  end

  private
  
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user  #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only:[:history]  

  def show
    @user = User.find(params[:id])
    @auctions = @user.active_auctions.paginate(page: params[:auction_page], per_page:3)
    if current_user && current_user.id.to_s == params[:id]
      @bids = @user.active_bids.includes(:auction).paginate(page: params[:bid_page], per_page:5)
    end
  end

  def history
    @user = User.find(params[:id])
    @my_old_auctions = current_user.auctions.expired.paginate(page: params[:old_auctions_page], per_page:10)
    @auctions_won = @user.auctions_won.paginate(page: params[:auctions_won_page], per_page: 5)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def profile_thumb_url(user)
    if user.picture.url && user.picture.thumb.url
      user.picture.thumb.url
    else
      'user-thumb.png'
    end
  end

  def profile_pic_url(user)
    if user.picture.url
      user.picture.thumb.url
    else
      'user-icon.png'
    end    
  end
end

app/views/users/_active_auctions.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="title text-center">
      <i class="fa fa-gavel"></i> Active Auctions
    </div>
    <div class="row">
      <%= render @auctions %>
    </div>  
    <div class="row text-center">
      <%= will_paginate @auctions, param_name:'auction_page', renderer: BootstrapPagination::Rails  %>
    </div>
 </div>
</div>    

app/views/users/_auction_row.html.erb
<tr>
  <td>
    <%= link_to auction_path(auction) do%>
      <i class="fa fa-gavel"></i> <%=auction.name%>
    <% end %>
  </td>
  <td>
    <%=distance_of_time_in_words_to_now(auction.end_time) %> ago
  </td>
</tr>

app/views/users/_auctions_table.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="title text-center">
      <i class="fa fa-gavel"></i> <%= title %> 
    </div>
    <table class="table">
      <tr>
        <th>Auction Name</th>
        <th>End Time</th>
      </tr>
      <% auctions.each do |auction| %>
        <%= render partial:'auction_row', locals:{auction: auction} %>
      <% end %>
    </table>
    <div class="row text-center">
      <%= will_paginate auctions, param_name: param_name, renderer: BootstrapPagination::Rails %>
    </div>
 </div>
</div>

app/views/users/_bid.html.erb
<tr>
  <td>
    <%=link_to auction_path(bid.auction) do%>
      <i class="fa fa-gavel"></i> <%=bid.auction.name%>
    <% end %>
  </td>
  <td><%=distance_of_time_in_words_to_now(bid.auction.end_time)%></td>
  <td><%=time_ago_in_words(bid.created_at)%></td>
  <td><%=bid.bid_amount%></td>
</tr>

app/views/users/_bids_table.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="title text-center">
      <i class="fa fa-money"></i> My Active Bids 
    </div>
    <table class="table">
      <tr>
        <th>Auction Name</th>
        <th>Auction End Time</th>
        <th>Bid Time</th>
        <th>Bid Amount</th>
      </tr>
      <% @bids.each do |bid| %>
        <%= render partial:'users/bid', locals:{bid:bid} %>
      <% end %>
    </table>

    <div class="row text-center">
      <%= will_paginate @bids, param_name: 'bid_page', renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>

app/views/users/_contacts.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="title text-center">
      <i class="fa fa-fax"></i> Contacts 
    </div>
    <table class="table text-center">
      <tr>
        <td><i class="fa fa-envelope-square"></i> Email:</td>
        <td><%= @user.email%></td>
      </tr>
    </table>
  </div>
</div>

app/views/users/_my_bid.html.erb
<tr>
  <td>
    <%=link_to auction_path(bid.auction) do%>
      <i class="fa fa-gavel"></i> <%=bid.auction.name%>
    <% end %>
  </td>
  <td><%=distance_of_time_in_words_to_now(bid.auction.end_time)%></td>
  <td><%=time_ago_in_words(bid.created_at)%></td>
  <td><%=bid.bid_amount%></td>
</tr>

app/views/users/_my_bids.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="title text-center">
      <i class="fa fa-money"></i> My Bids
    </div>
    <table class="table">
      <tr>
        <th>Auction Name</th>
        <th>Auction End Time</th>
        <th>Bid Time</th>
        <th>Bid Amount</th>
      </tr>
      <% @my_bids.each do |bid| %>
        <%= render partial:'my_bid', locals: {bid: bid} %>
      <% end %>
    </table>
  </div>
</div>

app/views/users/history.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="title text-center">
    <i class="fa fa-smile-o"></i> <%= @user.display_name.capitalize%>
  </div>
  <%=link_to user_path(current_user), class:"btn btn-default btn-sm" do%>
    <i class="fa fa-long-arrow-left"></i> Back
  <% end %>
  </br>
  </br>
    <%= render partial:'auctions_table', 
      locals: {auctions: @auctions_won, param_name:'auctions_won_page', title: 'Auctions I Won'} %>
    <%= render partial:'auctions_table', 
      locals: {auctions: @my_old_auctions, param_name:'old_auctions_page', title:'My Old Auctions'} %>  
 
</div>

app/views/users/show.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="title text-center">
    <i class="fa fa-smile-o"></i> <%= @user.display_name.capitalize%>
  </div>
  <%= render partial:'shared/profile_pic', locals: {resource: @user} %>

  <% if current_user == @user %>
    <%= link_to history_user_path(current_user), class:"btn btn-default btn-sm" do %>
      <i class="fa fa-archive"></i> My History
    <% end %>
  <% else %>
    <button class="pull-right btn btn-info btn-sm message-modal-opener">
      <i class="fa fa-envelope"></i> Send Message
    </button>
 
    <%= render partial:"shared/message_modal", locals: {user: @user} %>
  <% end %>

  <%= link_to user_reviews_path(@user), class: "btn btn-default btn-sm" do %>
    <i class="fa fa-commenting-o"></i> User Reviews
  <% end %>
  
  </br>
  </br>
  <% if current_user == @user %>
    <%= render 'bids_table'%>
  <% end %>
  <%= render 'active_auctions' %>
  <%= render 'contacts'%>
</div>