config/routes.rb
Rails.application.routes.draw do
  get 'bids/new'

  get 'bids/create'

  root 'static_pages#home'

  
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}, skip: :registrations
  devise_scope :user do 
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'user',
      path_names: { new: 'sign_up'},
      controller: 'registrations',
      as: :user_registration do 
        get :cancel
      end
  end

  resources :users, only: [:show] do
		member do
			get :history
    end
    resources :reviews, only: [:create, :destroy, :index]
    resources :notifications, only: [:index]
  end

  resources :conversations, only: [:index, :show]
  resources :messages, only: [:create]

  resources :auctions do
    member do
      get :history, :comments
    end
    resources :bids, only: [:new, :create]
    resources :comments, only: [:create, :destroy]
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController 
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :correct_user, only: [:destroy]

  def index
    @user = User.find(params[:user_id])
    @reviews = @user.reviews_received.order(created_at: :desc).includes(:giver).paginate(page:params[:page]).per_page(15)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @user = User.find(params[:user_id])
    @user.reviews_received.build(
      content: params[:review][:content], 
      giver: current_user,
      receiver: @user
    )
    if @user.save
      Notification.notify_new_review(@user, current_user)
      respond_to do |format|
        format.html {redirect_to user_reviews_path(@user)}
        format.js
      end
    else 
      flash[:failure] = "an error has occured while saving review"
      redirect_to user_reviews_path @user
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    render json: {id: params[:id]}
  end

  private
  
  def correct_user
    @review = Review.find(params[:id])
    redirect_to root_path unless @review.giver == current_user 
  end 
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def is_review_giver(review)
    return current_user == review.giver
  end
end

app/views/reviews/_review.html.erb
<div class="row comment" id="<%='review-'+review.id.to_s%>">
  <% if is_review_giver(review) %>
    <%=link_to user_review_path(@user,review), 
      remote:true, method: :delete, class: "close comment-close" do%>
      <span>&times;</span>
    <% end %>
  <% end %>


  <div class="col-md-3 text-center">
    <%= link_to user_path(review.giver), class:"thumb thumb-round" do %>
      <%= image_tag profile_thumb_url(review.giver) %>
    <% end %> 
    <div><%=review.giver.display_name.capitalize%></div>
  </div>

  <div class="col-md-9 comment-content light-text"> 
    <div><%=time_ago_in_words(review.created_at)%> ago</div>
    <%= review.content%>
  </div>
</div>

app/views/reviews/create.js.erb
$("#reviews").prepend("<%=j render @user.reviews_received.last %>").children(":first").hide().slideDown(500)
$("#review_body").val("")

app/views/reviews/index.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="title text-center">
    <i class="fa fa-commenting-o"></i> Review for <%= @user.display_name.capitalize%>
  </div>
  </br>

  <%= link_to user_path(@user), class: "btn btn-default btn-sm" do %>
    <i class="fa fa-long-arrow-left"></i> Back
  <% end %>
  </br>
  </br>

  <% if current_user && current_user != @user %>
    <%= form_for [@user, @user.reviews_received.new], remote:true do |f| %>
      <fieldset>
        <%= f.text_area :content, row:2, placeholder: "Leave a review...", class: "form-control", id:"review_body" %>
        <%= button_tag type: "submit", class: "btn btn-primary btn-sm" do %>
          Post Review <i class="fa fa-star-o"></i>
        <% end %>
      </fieldset>
    <% end %>
  <% end %>
  </br>

  <div id="reviews" class="comments">
    <%= render @reviews %>
  </div>
  
  <div class="row center-text endless-scroll">
    <%= will_paginate @reviews, renderer: BootstrapPagination::Rails %>
  </div>
  </br> 
  
</div>

app/views/reviews/index.js.erb
$('#reviews').append("<%= j render(@reviews) %>");
<% if @reviews.next_page %>
  $('pagination').replaceWith('<%=j will_paginate @reviews, renderer: BootstrapPagination::Rails %>');
<% else %>
  $('.pagination').remove();
<% end %>