config/routes.rb
Rails.application.routes.draw do
  get 'bids/new'

  get 'bids/create'

  root 'static_pages#home'

  
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}, skip: :registrations
  devise_scope :user do 
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'user',
      path_names: { new: 'sign_up'},
      controller: 'registrations',
      as: :user_registration do 
        get :cancel
      end
  end

  resources :users, only: [:show] do
		member do
			get :history
    end
    resources :reviews, only: [:create, :destroy, :index]
    resources :notifications, only: [:index]
  end

  resources :conversations, only: [:index, :show]
  resources :messages, only: [:create]

  resources :auctions do
    member do
      get :history, :comments
    end
    resources :bids, only: [:new, :create]
    resources :comments, only: [:create, :destroy]
  end

end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%=message_type%> text-center"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="row">
  </div>
  <div class="text-center">
    Made with <i class="fa fa-heart"></i> in Toronto
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#account-setting" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, id: "logo", class:"navbar-brand" do %>
        <i>Tec</i> <i class="fa fa-book"></i> <i>Tec</i>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="account-setting">
        <ul class="nav navbar-nav navbar-right">
          
          <li class="<%= is_active?('auctions', :action, 'index') %>">
            <%= link_to auctions_path, class:"bright-text" do%>
              <i class="fa fa-compass"></i> Explore
            <% end %>
          </li>
          
          <li class="<%= is_active?('auctions', :action, 'new') %>">
            <%= link_to new_auction_path do%>
              <i class="fa fa-file-o"></i> New Auction
            <% end %>
          </li>
          
          <li class="<%= is_active?('notifications', :action, 'index') %>">
            <%= link_to user_notifications_path(current_user) do %>
              <i class="fa fa-bell-o"></i>
              <% if current_user.unread_notification_count && current_user.unread_notification_count > 0 %>
                <span class="badge"><%=current_user.unread_notification_count%></span>
              <% end %> 
            <% end %>
          </li>          

          <li class="<%= is_active?('conversations', :action, 'index') %>">
            <%= link_to conversations_path do %>
              <i class="fa fa-envelope"></i>
              <% if current_user.unread_message_count && current_user.unread_message_count > 0 %>
                <span class="badge"><%=current_user.unread_message_count%></span>
              <% end %> 
             <% end %>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              Account <i class="fa fa-user"></i>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Profile", user_path(current_user) %></li>
              <li><%= link_to "Account Setting", edit_user_registration_path%></li>
              <li role="separator" class="divider"></li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do%>
                  <i class="fa fa-sign-out"></i> Sign Out
                <% end %>
              </li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    <% else %>
      <div class="collapse navbar-collapse" id="account-setting">
        <ul class="nav navbar-nav navbar-right">
          <li class="<%= is_active?('auctions', :action, 'index') %>">
            <%= link_to auctions_path, class:"bright-text" do%>
              <i class="fa fa-compass"></i> Explore
            <% end %>
          </li>
          <li class="<%= is_active?('registrations', :action, 'new') %>">
            <%= link_to "Sign Up", new_user_registration_path %>
          </li>
          <li class="<%= is_active?('devise/sessions', :action, 'new') %>">
            <%= link_to new_user_session_path do %>
              <i class="fa fa-sign-in"></i> Sign In
            <% end %>
          </li>
          <li>
            <%= link_to user_omniauth_authorize_path(:facebook) do %>
              <i class="fa fa-facebook-official"></i> Facebook Sign In
            <% end %>
          </li>
        </ul>
      </div>
    <% end %>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TextBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
	<div class="container container-body">
    <%= render 'layouts/flash' %>
    <div id="content"><%= content_for?(:content) ? yield(:content) : yield %></div>
	</div>
</body>
</html>

app/views/layouts/static_pages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TextBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
	<div class="container-fluid container-fluid-body">
		<%= render 'layouts/flash' %>
    <%= content_for?(:content) ? yield(:content) : yield %>
	</div>
  <%= render 'layouts/footer'%>
</body>
</html>